/**
 * Generates a valid ICC v2 RGB matrix-shaper profile (sRGB-compatible:
 * sRGB primaries chromatically adapted to D50, gamma 2.2 curves) for use as
 * a PDF/A OutputIntent DestOutputProfile. Built from scratch — no binary blobs.
 */

const S15F16 = (v: number): number => Math.round(v * 65536);

function writeU32(view: DataView, offset: number, value: number): void {
  view.setUint32(offset, value >>> 0, false);
}

function writeTag(bytes: Uint8Array, offset: number, tag: string): void {
  for (let i = 0; i < 4; i++) bytes[offset + i] = tag.charCodeAt(i);
}

function xyzTagData(x: number, y: number, z: number): Uint8Array {
  const out = new Uint8Array(20);
  const view = new DataView(out.buffer);
  writeTag(out, 0, 'XYZ ');
  writeU32(view, 8, S15F16(x));
  writeU32(view, 12, S15F16(y));
  writeU32(view, 16, S15F16(z));
  return out;
}

function curveTagData(gamma: number): Uint8Array {
  const out = new Uint8Array(14); // 12 + 2 (one u8Fixed8 entry), padded by caller
  const view = new DataView(out.buffer);
  writeTag(out, 0, 'curv');
  writeU32(view, 8, 1);
  view.setUint16(12, Math.round(gamma * 256), false);
  return out;
}

function descTagData(text: string): Uint8Array {
  const ascii = text + '\0';
  const size = 4 + 4 + 4 + ascii.length + 4 + 4 + 2 + 1 + 67;
  const out = new Uint8Array(size);
  const view = new DataView(out.buffer);
  writeTag(out, 0, 'desc');
  writeU32(view, 8, ascii.length);
  for (let i = 0; i < ascii.length; i++) out[12 + i] = ascii.charCodeAt(i);
  // unicode language code, unicode count, scriptcode, mac count + 67-byte field: all zero
  return out;
}

function textTagData(text: string): Uint8Array {
  const ascii = text + '\0';
  const out = new Uint8Array(8 + ascii.length);
  writeTag(out, 0, 'text');
  for (let i = 0; i < ascii.length; i++) out[8 + i] = ascii.charCodeAt(i);
  return out;
}

const pad4 = (n: number): number => (n + 3) & ~3;

/** Builds the complete profile. ~600 bytes, validates as ICC v2. */
export function buildSrgbIccProfile(): Uint8Array {
  // sRGB primaries Bradford-adapted to D50 (standard ICC values).
  const tags: Array<{ sig: string; data: Uint8Array }> = [
    { sig: 'desc', data: descTagData('Vikings sRGB') },
    { sig: 'cprt', data: textTagData('No copyright, generated by Vikings Master PDF') },
    { sig: 'wtpt', data: xyzTagData(0.9642, 1.0, 0.8249) },
    { sig: 'rXYZ', data: xyzTagData(0.436, 0.2225, 0.0139) },
    { sig: 'gXYZ', data: xyzTagData(0.3851, 0.7169, 0.0971) },
    { sig: 'bXYZ', data: xyzTagData(0.1431, 0.0606, 0.7139) },
    { sig: 'rTRC', data: curveTagData(2.2) },
    { sig: 'gTRC', data: curveTagData(2.2) },
    { sig: 'bTRC', data: curveTagData(2.2) }
  ];

  const headerSize = 128;
  const tagTableSize = 4 + tags.length * 12;
  let dataOffset = headerSize + tagTableSize;
  const offsets: number[] = [];
  for (const t of tags) {
    offsets.push(dataOffset);
    dataOffset += pad4(t.data.length);
  }
  const totalSize = dataOffset;

  const profile = new Uint8Array(totalSize);
  const view = new DataView(profile.buffer);

  // ── Header
  writeU32(view, 0, totalSize);
  writeU32(view, 8, 0x02100000); // version 2.1
  writeTag(profile, 12, 'mntr');
  writeTag(profile, 16, 'RGB ');
  writeTag(profile, 20, 'XYZ ');
  const now = new Date();
  view.setUint16(24, now.getUTCFullYear(), false);
  view.setUint16(26, now.getUTCMonth() + 1, false);
  view.setUint16(28, now.getUTCDate(), false);
  view.setUint16(30, now.getUTCHours(), false);
  view.setUint16(32, now.getUTCMinutes(), false);
  view.setUint16(34, now.getUTCSeconds(), false);
  writeTag(profile, 36, 'acsp');
  // Illuminant: D50.
  writeU32(view, 68, S15F16(0.9642));
  writeU32(view, 72, S15F16(1.0));
  writeU32(view, 76, S15F16(0.8249));

  // ── Tag table
  writeU32(view, headerSize, tags.length);
  tags.forEach((t, i) => {
    const entry = headerSize + 4 + i * 12;
    writeTag(profile, entry, t.sig);
    writeU32(view, entry + 4, offsets[i]!);
    writeU32(view, entry + 8, t.data.length);
  });

  // ── Tag data
  tags.forEach((t, i) => {
    profile.set(t.data, offsets[i]!);
  });

  return profile;
}
